add_newline = true
format = "$username$hostname$directory$git_branch$git_status$character"
[username]
show_always = true
style_user = "bold blue"
style_root = "bold red"
format = "[$user]($style)[@](bright-black)"
[hostname]
ssh_only = false
style = "bold cyan"
format = "[$hostname]($style) "
[directory]
style = "bold yellow"
truncation_length = 3
[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
[git_branch]
style = "purple"
[git_status]
style = "yellow"
